### ISSUE TITLE
Changing model doesn't work on Windows

### ISSUE THREAD

**Issue by fbgallet** [LayBacc/roam-ai#5]
![image](https://user-images.githubusercontent.com/74436347/198058585-1949555f-115d-4e10-93a1-22ea799b5047.png)

Command key doesn't exist on PC, you should add Ctrl key in the corresponding eventlistener!

By the way, what is the syntax for 'Custom models' in the panel settings ? Is there a documentation ? On Open AI web site, 'endpoint' is presented as deprecated.

**Comment by Stvad** [comment]
It doesn't work for me on Mac either :p

**Comment by Stvad** [comment]
it seems the davinci-2 is the only model defined in the code rn
https://github.com/LayBacc/roam-ai/commit/fea9d000985efe207ba84efe1045d083d867bc6b

**Comment by LayBacc** [comment]
@fbgallet @Stvad sorry about the delay!

the `endpoint` parameter is [used internally by the plugin](https://github.com/LayBacc/roam-ai/blob/master/src/index.ts#L65)

and for davinci-003, we don't need the `endpoint` param (since the default is OpenAI)

the format for configuring custom models then looks like this: 
`[{ "name": "model A", "displayName": "model A", "model": "model-001" }]`

in the next release, I'll update the default to davinci-003
